name: $(Date:yyyyMMdd)$(Rev:.r)
variables:
  linuxImage: 'ubuntu-16.04'
  windowsImage: 'vs2017-win2016'

stages:
- stage: RestoreAndBuild
  jobs:
  - job: BuildJob
    strategy:
      matrix:
        linux:
          imageName: $(linuxImage)
        windows:
          imageName: $(windowsImage)

    pool:
      vmImage: $(imageName)

    steps:
    - script: |
        dotnet restore
        dotnet build -c Release

- stage: Test
  jobs:
  - job: TestOnWindows
    steps:
    - script: echo Testing on Windows!
  - job: TestOnLinux
    steps:
    - script: echo Testing on Linux!

- stage: Deploy
  jobs:
  - job: Deploy
    steps:
    - script: echo Deploying the code!
    
