strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.13'
    windows:
      imageName: 'vs2017-win2016'

pool:
  vmImage: $(imageName)

steps:
- script: dotnet restore

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration Release'


- task: VSTest@2
  displayName: 'Run Unit tests'
  inputs:
    testAssemblyVer2: |
     **\*Test*.dll
     !**\*Integration.Test*.dll
     !**\*TestAdapter.dll
     !**\obj\**
    otherConsoleOptions: '/Framework:".NETCoreApp,Version=v2.1" /Blame '

    platform: '$(BuildPlatform)'

    configuration: 'Release'

    rerunFailedTests: true
    
- task: VSTest@2
  displayName: 'Run Integration tests'
  inputs:
    testAssemblyVer2: |
     **\*Integration.Test*.dll
     !**\*TestAdapter.dll
     !**\obj\**
    otherConsoleOptions: '/Framework:".NETCoreApp,Version=v2.1" /Blame '

    platform: '$(BuildPlatform)'

    configuration: 'Release'

    rerunFailedTests: true

