version: '2'

services:
  anabi-gestiune-api:
    image: anabi-gestiune-api
    build: .
    ports:
      - 3000:3000
    depends_on:
            - db
  db:
      image: "microsoft/mssql-server-linux"
      environment:
          SA_PASSWORD: "Puiu2108####"
          ACCEPT_EULA: "Y"